### ISSUE TITLE
Feature #1: User can create a profile

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/lfz-final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a profile that will allow retrieval of saved data in the future.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will create a login account using first name, last name, email, and password.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/171272911-444f42ce-3736-4d82-880c-14ad670bbdbe.png)
![image](https://user-images.githubusercontent.com/96906988/171272956-9f416b20-4546-4302-b5ad-e25cfe83a261.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Add initial SQL to "schema.sql" to create all tables in the database

### ☁️ Server

- [x] Create endpoint "POST /api/profiles" to save a user's profile to database

### ⚡ Client

- [x] Create a component to allow users to create an account

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
