### ISSUE TITLE
Feature #2: User can create a job they have applied to

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/lfz-final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an entry for a job that has been applied to.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create a job entry to keep track of the status and progress during job search.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/171294155-584e091e-2c51-4856-a7fc-20cb7dbd6ea4.png)
![image](https://user-images.githubusercontent.com/96906988/171294192-3b88d9bc-a217-4420-a373-26bba88056ca.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

None.

### ☁️ Server

- [x] Create endpoint "POST /api/jobs" to save e a new user job entry to database.

### ⚡ Client

- [x] Create a component to offer a form for user to input data and for that data to be stored.

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
