### ISSUE TITLE
Feature #4: User can update the list of jobs

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/lfz-final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can update existing entries.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click dotted region on a job card to open edit form. Once edits are submitted, edit form will close and original dashboard will reflect the changes to the database.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/172975141-a3cf1c66-1c33-450b-b544-0aff94a90c89.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to process update requests to server
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render edit form.
- [x] Update dashboard component to re-render the cards with updated database.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
