### ISSUE TITLE
Feature #5: Users can delete an entry

### ISSUE THREAD

**Issue by theDanielYeh** [theDanielYeh/lfz-final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a saved entry.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can find a delete icon on the job card of interest. Upon click, a delete confirm modal will pop up. Confirm to successfully delete the data and return to deck of cards (dashboard).

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/96906988/173166204-5a30b9fa-d832-44d4-ac34-9605d7c959e9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to include app.delete requests.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for delete confirmation modal.
- [x] Update dashboard component to toggle delete confirm modal.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
